### PR TITLE
Fix: update preview when config change

### LINKED ISSUE #807: Changes to user-customizable variables don't take effect until style is edited and saved
* **Browser**: Firefox 70.0.1 (64-bit)
* **Operating System**: Windows 10, Manjaro
* **Stylus Version**: 1.5.6

When a user changes the value of a variable (the `@var` kind), the changes aren't applied to the website. Clicking the "save" button does nothing. Unchecking "on change" does nothing. Screenshot, for context:
image

You can see the green "accent color" in use in the background. If I change it to, say, orange and click "close", the changes are saved (re-opening the settings will show orange instead of green) but the website itself doesn't change and stays green:
image

Reloading the page has no effect. The only way to I've found to actually apply the changes is to open the style in the editor, make a change, undo the change and re-save the style.

### PR DESCRIPTION
**Pull request by eight04**
Fixes #807

### CODE REVIEW

File: edit/edit.js [hunk 1]
```diff
@@ -140,6 +140,7 @@ async function handleExternalUpdate({style, reason}) {
     delete style.name;
     delete style.enabled;
     Object.assign(editor.style, style);
+    editor.updateLivePreview();
```
Comment (tophf) [inline edit/edit.js:143]: This is wasteful because most of the work it does is thrown away (assembling the string from CodeMirror, serializing it when sending through `chrome` port, deserializing it in the background script). Can't you update the preview inside styleManager directly?

Comment (eight04) [reply edit/edit.js:143]: Currently, modified source code (in the editor) is compiled in the editor page, then compiled sections are sent to the background.

If we want to update the preview in the background, we can

1. write a `previewManager` that handles "raw" style (source code) from the editor.
2. `previewManager` would compile the "raw" style and send the result to`styleManager`.
3. We can create some new API like `styleManager.installPreview()/uninstallPreview()` that can be used by `previewManager`.

Then, we can make `previewManager` listen to `styleUpdated` to re-compile the preview on config change.

The editor:

1. pipe its "raw" style to `previewManager`.
2. We can remove all the live preview logic from the editor.
3. It only needs to handle the UI. (`live preview` checkbox)

**Comment by eight04** [comment]
BTW have you found why it can't be reproduced on your side? which might be another bug.

File: edit/edit.js (hunk 1 above)
Comment (eight04) [reply edit/edit.js:143]: Oh and this pattern is similar to how we handle live reload when opening a `.user.css` file locally. We can probably merge them into a single service in the future.

Comment (tophf) [reply edit/edit.js:143]: For now, skipping the call if the editor's style id is the same as the id in the message should be enough.

**Comment by tophf** [comment]
> BTW have you found why it can't be reproduced on your side? which might be another bug.

I can't find what I can't reproduce :-)

File: edit/edit.js (hunk 1 above)
Comment (tophf) [reply edit/edit.js:143]: I guess not, because the goal is to re-build the preview... Well then merge it as-is.

**Comment by eight04** [comment]
https://github.com/openstyles/stylus/issues/807#issuecomment-1462386791

Since your edits got reverted, I guess something went wrong in the editor. Stylus doesn't revert user edits without prompts.

You can try tracking what message the editor receives
https://github.com/openstyles/stylus/blob/1d2f384bb95b11c6fb965096bd448fe2fcb96831/edit/edit.js#L117
and how the editor handles the message.

**Comment by tophf** [comment]
No, not my edits, but the effect of the style on the page. When I added `background: white` in the editor it showed up in the page, then I configured the style in the popup and it removed the background.
