### PR TITLE
Fix: less intrusive authorization

### LINKED ISSUE #1115: Sync login error, the dialog appears and closes repeatedly
popups for drive login, which is failed, but keep flashing all the time, was very hard to figure that out, since it closes almost immediately

### LINKED ISSUE #1152: Improve handling of sync error "User interaction required"
Problem per https://github.com/openstyles/stylus/issues/860#issuecomment-757430437

> `User interaction required.`

>the connected button is grey, seems to be connected but actually not
click "sync now" gives no response
click disconnect and connect solve the problem temporarily

Possible solution per https://github.com/openstyles/stylus/issues/860#issuecomment-757433850

1. Have a better error message like `Session is expired. Please login again.`
2. Disable `sync now` button when `!state.login`. https://github.com/openstyles/stylus/blob/fe176c9b62bb664628ba2e440f80d96437e84cce/options/options.js#L150

### PR DESCRIPTION
**Pull request by eight04**
Fixes #1152 
Fixes #1115 without fixing Vivaldi.

Ready for review/merge but I'd like to fix https://github.com/eight04/db-to-cloud/issues/17 before merging this.

### CODE REVIEW

**Review by tophf — APPROVED** [review]
Seems to work for me but I don't know how to test those problematic scenarios that are fixed by this PR...

**Comment by eight04** [comment]
I set an invalid token:
```js
await browser.storage.local.set({"secure/token/google/token": "1234"});
```

**Comment by tophf** [comment]
Tried setting an invalid token with **dropbox**: Stylus indicates a generic "Sync failed" status, which is probably not helpful. The network request fails with `400 Bad Request` code so maybe it's sufficient to consider it a login failure?

**Comment by eight04** [comment]
Just tested with dropbox. I got an error like this when setting the token to `1234`:
```
failed to fetch [400]: Error in call to API function "files/download": The given OAuth 2 access token is malformed.
```
I get 401 error if I only change a single character in the token. Apparently the server throws different errors in different phases e.g. parsing token, validation, etc.

I'm not sure if there is a good way to identify all of them. 400 is a general request error so I don't think we should consider it as a login error.

**Comment by narcolepticinsomniac** [comment]
> not sure if there is a good way to identify all of them

Could we not use a basic regex check for certain keys/words/phrases to differentiate between general request errors, and login errors?

**Comment by tophf** [comment]
I'd say the first practical step in solving any `400` error is to re-login so why don't why suggest it? Other than that the PR seems fine.

**Comment by narcolepticinsomniac** [comment]
> the first practical step in solving any 400 error is to re-login

I thought the concern was that general request errors could happen randomly for any number of reasons, but typically for temporary connectivity issues, in which case, the token is still fine once the connection is reestablished.

**Comment by tophf** [comment]
Connectivity issues don't return `400` AFAICT.

**Comment by narcolepticinsomniac** [comment]
Shows what I know. =) Not like I'm testing any of this personally, I thought I was reiterating one of @eight04's concerns. He obviously thought some 400's could, and should be ignored. Which responses those would be exactly, is purely speculation on my part.

If there are some that should be ignored, there should be a way to check for, or against certain responses. Otherwise, yeah, I guess we notify on any 400 and move on.

**Comment by eight04** [comment]
Currently we have 3 types of errors.

1. network errors - which are ignored.
2. login errors - which are shown on the icon and we ask users to re-log.
3. other errors - which are shown on the icon.

Note that when (2) happens, users will be logout i.e. it doesn't sync anymore. However for (1) and (3), we still try to sync every 30 minutes.

Currently login errors are limited to:

1. http 401 errors.
2. http 400 invalid grant errors - this happens when the (refresh) token is invalid/expired/revoked.

> I'd say the first practical step in solving any `400` error is to re-login so why don't why suggest it?

One potential problem to make all http 400 responses as login errors is that the user will be logout once getting them. I'm not really sure how often or how the user get a 400 error.

> Could we not use a basic regex check for certain keys/words/phrases to differentiate between general request errors, and login errors?

The message I shown in https://github.com/openstyles/stylus/pull/1172#issuecomment-776760787 happens when 1) using dropbox 2) setting the token to `1234`. IDK what will the server response for other situations.

**Comment by narcolepticinsomniac** [comment]
Well, if these potential problems and responses are currently purely hypothetical, I suppose we should treat all 400's as problematic. We can tweak that in the future if it's warranted, and we have more to go on.

**Comment by tophf** [comment]
Fine, let's only process known codes and extend the logic only when someone reports a new code to us. Still, `Sync failed` tooltip isn't helpful so I'd say it should be followed by the actual error text e.g. `'\n' + lastError.message`

File: background/sync-manager.js [hunk 1]
```diff
@@ -223,11 +218,12 @@ const syncMan = (() => {
...
 
   function getErrorBadge() {
-    if (status.state === STATES.connected && lastError && !isNetworkError(lastError)) {
+    if (status.state === STATES.connected &&
+        (!status.login || lastError && !isNetworkError(lastError))) {
       return {
         text: 'x',
         color: '#F00',
-        title: isGrantError(lastError) ? 'syncErrorRelogin' : 'syncError',
+        title: !status.login ? 'syncErrorRelogin' : 'syncError',
```
Comment (elamperti) [inline background/sync-manager.js:226]:
```suggestion
        title: status.login ? 'syncError' :  'syncErrorRelogin',
```

File: background/sync-manager.js [hunk 2]
```diff
@@ -63,19 +63,19 @@ const syncMan = (() => {
       return status;
     },
 
-    async login(name = prefs.get('sync.enabled')) {
+    async login(name) {
       if (ready.then) await ready;
+      if (!name) name = prefs.get('sync.enabled');
```
Comment (elamperti) [inline background/sync-manager.js:68]: Why did you change this?

File: _locales/en/messages.json [hunk 3]
```diff
@@ -1141,6 +1141,9 @@
   "optionsSyncStatusDisconnected": {
     "message": "Disconnected"
   },
+  "optionsSyncStatusRelogin": {
+    "message": "Session is expired. Please login again."
```
Comment (elamperti) [inline _locales/en/messages.json:1145]: Minor suggestion:

```suggestion
    "message": "Session expired, please login again."
```

File: background/sync-manager.js [hunk 4]
```diff
@@ -192,21 +202,6 @@ const syncMan = (() => {
     });
   }
 
-  async function handle401Error(err) {
-    let authError = false;
-    if (err.code === 401) {
-      await tokenMan.revokeToken(currentDrive.name).catch(console.error);
-      authError = true;
-    } else if (/User interaction required|Requires user interaction/i.test(err.message)) {
```
Comment (elamperti) [inline background/sync-manager.js:200]: Where are you catching this case? `isGrantError` is only checking for a 401 status

File: background/sync-manager.js [hunk 5]
```diff
@@ -63,19 +63,19 @@ const syncMan = (() => {
       return status;
     },
 
-    async login(name = prefs.get('sync.enabled')) {
+    async login(name) {
       if (ready.then) await ready;
+      if (!name) name = prefs.get('sync.enabled');
+      await tokenMan.revokeToken(name);
```
Comment (elamperti) [inline background/sync-manager.js:69]: What if this call fails?

**Review by elamperti — CHANGES_REQUESTED** [review]
Thanks for your work towards fixing this auth issue!

File: background/sync-manager.js (hunk 1 above)
Comment (tophf) [reply background/sync-manager.js:226]: Looks like an attempt to adhere to [no-negated-condition](https://eslint.org/docs/rules/no-negated-condition) eslint rule. Don't propose such cosmetic changes, it only slows down development. The proper way for you to become a permanent contributor and propose PRs that handle such issues globally but first we all should discuss in a new issue if we want a particular cosmetic change.

File: background/sync-manager.js (hunk 2 above)
Comment (tophf) [reply background/sync-manager.js:68]: Because `prefs` may be not ready. Look at git blame before asking.

File: background/sync-manager.js (hunk 5 above)
Comment (tophf) [reply background/sync-manager.js:69]: Look at the code of revokeToken: if it fails then something is so wrong that catching it won't change a thing.

File: background/sync-manager.js (hunk 4 above)
Comment (tophf) [reply background/sync-manager.js:200]: Why are you commenting in removed code?

File: background/sync-manager.js (hunk 5 above)
Comment (eight04) [reply background/sync-manager.js:69]: `revokeToken` itself ignores fetch errors. If other services fail e.g. `storage.remove` then the user won't be able to login.

File: background/sync-manager.js (hunk 4 above)
Comment (eight04) [reply background/sync-manager.js:200]: This case no longer exists. We disallow implicit auth in `token-manager.js` and stop background sync if `!status.login`.

File: background/sync-manager.js (hunk 1 above)
Comment (elamperti) [reply background/sync-manager.js]: I was not trying to adhere to a particular linting rule, only to avoid an unnecessary negation of `status.login`, but your explanation in the last paragraph makes sense. My code review was aimed to help, not to impose cosmetic changes.

File: background/sync-manager.js (hunk 2 above)
Comment (elamperti) [reply background/sync-manager.js:68]: > Because prefs may be not ready.
This makes sense, I didn't know waiting for `ready` would solve it.

> Look at git blame before asking.
I spent a good time looking at the PR before posting my comments, and I may have asked unnecessary questions because I'm unfamiliar with the code. No need for hostility :) I was just trying to help with my time; I won't get in the way anymore. Cheers

Comment (tophf) [reply background/sync-manager.js:68]: I'm not hostile per se, just implicitly unwelcoming to such kind of reviews.
