### PR TITLE
Fix: compatible with kiwi

### LINKED ISSUE #1367: [Bug] Does not install .user.css files in Kiwi Browser on Android
# Bug Report

### Bug Description

On desktop, I am used to install user CSS by clicking the _Raw_ button on GitHub hosted `.user.css` files.
It does trigger the Stylus install process.

But **on [Kiwi Browser](https://kiwibrowser.com) on Android**, where I have installed Stylus, **clicking the _View raw_ button of a `.user.css` file** on GitHub, **does not trigger the install process.**

I'm therefore clueless as to how to install my user styles.

URL of an example `.user.css` file: https://github.com/jesus2099/konami-command/blob/master/metabrainz-discourse_EXPAND-ABBREVIATIONS.user.css (click RAW button on desktop or … (ellipsis) button on mobile, then _View raw_)

### System Information

- OS: Android 9
- Browser: Kiwi Browser 96.0.4664.46
- Stylus Version: 1.5.22

### Additional information

For what it's worth:

- It does work on Firefox for Android 68.11.0 with Stylus 1.5.21
- Violentmonkey does install `.user.js` user scripts when clicking _View raw_ on same Kiwi Browser

### PR DESCRIPTION
**Pull request by eight04**
Fixes #1367

### CODE REVIEW

File: background/usercss-install-helper.js [hunk 1]
```diff
@@ -96,28 +96,35 @@ bgReady.all.then(() => {
     const u = new URL(url);
     const m = maybeDistro[u.hostname];
     if (!m || m.rx.test(u.pathname)) {
-      openInstallerPage(tabId, url, {});
+      openInstallerPage(tabId, url, {}).catch(console.error);
       // Silently suppress navigation.
       // Don't redirect to the install URL as it'll flash the text!
-      return {redirectUrl: 'javascript:void 0'}; // eslint-disable-line no-script-url
+      return {cancel: true};
```
Comment (eight04) [inline background/usercss-install-helper.js:102]: Without this change, the installer is opened twice in kiwi. It seems that `redirectUrl` only works with `onBeforeRequest` or `onHeadersReceived` according to MDN:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/BlockingResponse

File: background/usercss-install-helper.js [hunk 2]
```diff
@@ -96,28 +96,35 @@ bgReady.all.then(() => {
     const u = new URL(url);
     const m = maybeDistro[u.hostname];
     if (!m || m.rx.test(u.pathname)) {
-      openInstallerPage(tabId, url, {});
+      openInstallerPage(tabId, url, {}).catch(console.error);
```
Comment (tophf) [inline background/usercss-install-helper.js:99]: Try using a global `unhandledrejection` handler instead.

File: .gitignore [hunk 3]
```diff
@@ -4,5 +4,6 @@ pull_locales_login.rb
 node_modules/
 yarn.lock
 *.zip
+*.log
```
Comment (tophf) [inline .gitignore:7]: Why? Do we have something that generates log files?

File: background/usercss-install-helper.js [hunk 4]
```diff
@@ -96,28 +96,35 @@ bgReady.all.then(() => {
...
-          active: tab.active,
-          index: tab.index + 1,
-          openerTabId: tabId,
-          currentWindow: null,
-        }));
-    } else {
-      const timer = setTimeout(clearInstallCode, 10e3, url);
-      installCodeCache[url] = {code, timer};
-      chrome.tabs.update(tabId, {url: newUrl});
+      const tab = browser.tabs.get(tabId);
```
Comment (tophf) [inline background/usercss-install-helper.js:109]: await

File: background/usercss-install-helper.js [hunk 5]
```diff
@@ -96,28 +96,35 @@ bgReady.all.then(() => {
...
+        openerTabId: tabId,
+        currentWindow: null,
+      });
+    }
+    const timer = setTimeout(clearInstallCode, 10e3, url);
+    installCodeCache[url] = {code, timer};
+    try {
+      await browser.tabs.update(tabId, {url: newUrl});
+    } catch (err) {
+      // FIXME: https://github.com/openstyles/stylus/issues/1367
```
Comment (tophf) [inline background/usercss-install-helper.js:123]: It's very inconvenient when a comment is a riddle that needs you to open an external page with a lot of comments and spend time to make sense of it.

Since you've used FIXME, it means a better fix is needed or we need to revisit this when Kiwi fixes itself. In that case write it explicitly. If it's just informational then use `Kiwi bug workaround` instead of FIXME.

**Review by tophf — CHANGES_REQUESTED** [review]

File: background/usercss-install-helper.js (hunk 2 above)
Comment (eight04) [reply background/usercss-install-helper.js:99]: Isn't that a bad idea since it will log all kinds of uncaught promises including 3rd-party libraries?

Comment (eight04) [reply background/usercss-install-helper.js:99]: Also I think this event should only be handled at debug time e.g. execute some code in console like
```js
document.addEventListener("unhandledrejection", e => console.dir(e))
```
Instead of coding it in the repo.

File: .gitignore (hunk 3 above)
Comment (eight04) [reply .gitignore:7]: I got some logs while debugging android browsers. Do you want to revert this change?

File: background/usercss-install-helper.js (hunk 2 above)
Comment (tophf) [reply background/usercss-install-helper.js:99]: On the contrary, it sounds like something useful. We don't many external libraries in the background script so if any of them aren't handling rejections then maybe there's something suspicious in their code that needs to be fixed.

Comment (tophf) [reply background/usercss-install-helper.js:99]: Another solution is to add the call stack to the error thrown inside `browser` polyfill ([example](https://github.com/violentmonkey/violentmonkey/blob/master/src/common/browser.js#L56)). It won't work in Firefox, obviously, but maybe it prints a usable call stack by default.

In any case, I'm strongly against peppering the code with explicit console calls.

**Comment by eight04** [comment]
Done.

I'm curious about why you don't like console API? What if we send the error to an error logger/collector created by ourselves?

File: .gitignore (hunk 3 above)
Comment (eight04) [reply .gitignore]: I can't ignore all log files though I need them in other repos.

Comment (tophf) [reply .gitignore]: Well, then `.git/info/exclude` in the repo.

**Comment by tophf** [comment]
> I'm curious about why you don't like console API?

It pollutes the code.

> What if we send the error to an error logger/collector created by ourselves?

But we don't.

**Review by tophf — APPROVED** [review]
