### PR TITLE
Fix #1176 Installing local UserCSS style fails in Firefox

### LINKED ISSUE #1176: Installing local UserCSS style fails in Firefox
* **Browser**: Librewolf/Firefox 84
* **Operating System**: Linux
* **Stylus Version**: v1.5.15
* **Screenshot**: 
image

This only happens in Firefox-based browsers when installing from `file` URI scheme; Chromium-based browsers don't have this issue, so installing local UserCSS styles works fine. The error points to this function:
https://github.com/openstyles/stylus/blob/890ff395c09c5ded60bae29bd9ab0ac63772878f/install-usercss/install-usercss.js#L325-L334

### PR DESCRIPTION
**Pull request by vVde3S88xHW6EZaB63HyXQUipgFtaWooYGDs35g**
Following discussion in #1176 I've used `git bisect` to find the first failing commit as @tophf suggested. Starting from last good version `v1.5.13` reported by @vednoc I've arrived at commit 707cd6576f2d930211be50f21362027b6cb9e873 as the first bad commit.

From what I was able to get reading the code and reproducing the error state shown on [screenshot from original report](https://user-images.githubusercontent.com/18245694/107519428-8da8d400-6bb0-11eb-8df0-740161ec7c88.png), it looks like the error comes from changing the logic in `downloadSelf` event listener.

Old code used this condition for determining when to fill in `code` value of the msg passed:

```
.then(code => ({id, code: timer && code === self.oldCode ? null : code}))
```

while new logic uses something like this (note the use of `force` flag instead of `timer` and somewhat inverse nature of the logic):

```
.then(code => ({id, code: force || code !== self.oldCode ? code : null}))
```

What this patch does is applying both approaches: using `force` flag and using `timer` flag at the same time. As I am myself affected by this bug, and was able to successfully mitigate it in my environment (latest FireFox v87.0 on Linux), I can confirm that it solves the issue and now I'm able to install local files on FireFox again with this patch.

Please let me know if this pull request needs more formatting or additional commits, as the [contributions page](https://github.com/openstyles/stylus/blob/master/.github/CONTRIBUTING.md#pull-requests) didn't mention anything specific aside from `.editorconfig` codestyle which I think I didn't break here.

P.S.: There's a 39c1d61e11b78d5343218591ac7f5848cb3e82bb commit which claims to fix #1176 as well, but according to my tests it doesn't make much difference to help the bug and didn't actually solve it.

### CODE REVIEW

File: content/install-hook-usercss.js [hunk 1]
```diff
@@ -5,11 +5,11 @@ if (typeof window.oldCode !== 'string') {
   window.oldCode = (document.querySelector('body > pre') || document.body).textContent;
   chrome.runtime.onConnect.addListener(port => {
     if (port.name !== 'downloadSelf') return;
-    port.onMessage.addListener(async ({id, force}) => {
+    port.onMessage.addListener(async ({id, force, timer}) => {
       const msg = {id};
       try {
         const code = await (await fetch(location.href, {mode: 'same-origin'})).text();
-        if (code !== window.oldCode || force) {
+        if ((code !== window.oldCode || force) || !(timer && code === window.oldCode)) {
```
Comment (tophf) [inline content/install-hook-usercss.js:12]: `timer` is unused now so `!(timer && code === window.oldCode)` will always be true, meaning this PR doesn't actually change anything.

**Comment by vednoc** [comment]
Been using it for the last 10 minutes and it really is working! @tophf I apologize for completely forgetting to go back to it.

**Comment by tophf** [comment]
I'm assuming you mean Stylus works without this PR because it doesn't change anything.

File: content/install-hook-usercss.js (hunk 1 above)
Comment (tophf) [reply content/install-hook-usercss.js:12]: Er, I misread it: now this condition is always `true` which is plain wrong.

**Comment by tophf** [comment]
I misread the code in this PR: it sets the condition to be always true. So it does change the behavior, but it's wrong so I won't merge it in its current form.

**Review by tophf — CHANGES_REQUESTED** [review]
I misread the code in this PR: it sets the condition to be always true. So it does change the behavior, but it's wrong so I won't merge it in its current form.

**Comment by tophf** [comment]
Looking at the bad commit, which converts `timer` to `force`, the initial call was not converted:
image

So the correct fix would be to replace `timer: false` with `force: true`.

**Review by tophf — APPROVED** [review]

**Comment by tophf** [comment]
Does it work now?

**Comment by vVde3S88xHW6EZaB63HyXQUipgFtaWooYGDs35g** [comment]
@tophf yes, I confirm that with your latest changes in this branch the bug is gone for me. Thanks for looking into this and your prompt action.
