### PR TITLE
Fix usercss install error. Closes #589

### LINKED ISSUE #589: Error happened when installing usercss by dropping usercss files in the manager
* **Browser**: Cent Browser Version 3.7.2.33 (Official Build) (64-bit) (Chromium 70.0.3538.110)
* **Operating System**: Windows 7
* **Stylus Version**: Current master (43a4671c64dff)
* **Screenshot**:
image
image
I think the element was removed. Maybe we should use another way to inject the warning.

### PR DESCRIPTION
**Pull request by Mottie**
Previously all contents were replaced by text. This PR adds the text to the included span for both the update url and live reload blocks.

### CODE REVIEW

File: install-usercss/install-usercss.js [hunk 1]
```diff
@@ -16,7 +16,8 @@
   let port;
 
   if (params.has('direct')) {
-    $('.live-reload').textContent = t('liveReloadUnavailable');
+    $('.live-reload input').classList.add('hidden');
```
Comment (eight04) [inline install-usercss/install-usercss.js]: Can we fix this using CSS?
```css
.live-reload .unavailable-message {
	display: none;
}
.live-reload.unavailable .unavailable-message {
	display: inline;
}
.live-reload.unavailable input {
	display: none;
}
```
So we just have to toggle `unavailable` class in js.

Comment (Mottie) [reply install-usercss/install-usercss.js]: Yes, that's a much cleaner solution! 😸

**Comment by Mottie** [comment]
Excessive? Probably, but it should be fixed now.
