### PR TITLE
Fix & cleanup config in popup. Closes #602

### LINKED ISSUE #602: Non-usercss issue in popup
Copy the following CSS:

```css
/* ==UserStyle==
@name           _test_google
@namespace      Me
@version        1.0.0
@description    config in popup
@author         Me
==/UserStyle== */

@-moz-document domain("google.com") {
  body {
    color: red !important;
  }
}
```

1. Open **Chrome** (this issue doesn't happen in Firefox; I didn't test other browsers).
2. Open the manage page.
3. Uncheck the "as Usercss" next to write new style on the manager page.
4. Click the "Write new style" button, and the editor will open in a non-usercss mode.
5. Paste the above CSS into the editor and use "Overwrite style"; it should work right?
6. Enter any name & click Save.
7. Now open https://www.google.com
8. Open the popup and you'll see that the style includes a usercss config icon.
9. Click on the icon and the popup will open in a new tab.... so weird.

### PR DESCRIPTION
**Pull request by Mottie**
The configure icon code was spread out and confusing. This PR combines and cleans it up.

### CODE REVIEW

File: popup/popup.js [hunk 1]
```diff
@@ -276,15 +276,20 @@ function createStyleElement({
...
+
     const config = $('.configure', entry);
+    config.onclick = handleEvent.configure;
     if (!style.usercssData && style.updateUrl && style.updateUrl.includes('?') && style.url) {
+      config.href = style.url;
       config.target = '_blank';
       config.title = t('configureStyleOnHomepage');
       config.dataset.sendMessage = JSON.stringify({method: 'openSettings'});
       $('use', config).attributes['xlink:href'].nodeValue = '#svg-icon-config-uso';
+    } else if (style.usercssData && Object.keys(style.usercssData.vars || {}).length === 0) {
```
Comment (eight04) [inline popup/popup.js]: It doesn't hide the config button if the style is installed from USO and doesn't have configurable options.

Comment (Mottie) [reply popup/popup.js]: LOL Funny, I don't have any styles installed from USO anymore, so I forgot to check.

**Comment by Mottie** [comment]
@eight04 Does this PR need anything else?
