### PR TITLE
randomize sync interval to avoid infinite deadlocks

### LINKED ISSUE #1247: OneDrive Synchronisation gives sometimes 409
* **Browser**: Firefox
* **Operating System**: Windows 10 Pro
* **Stylus Version**: 1.5.17

I am using OneDrive to sync my styles, but sometimes (I don't know when exactly) I get the following error:
```
failed to fetch [409]: {"error":{"code":"nameAlreadyExists","message":"An item with the same name already exists under the parent","innerError":{"date":"2021-05-12T12:18:33","request-id":"SOME-FUNNY-ID","client-request-id":"ANOTHER-FUNNY-ID"}}}
```

It helps to delete every file from the `Applications/Stylus` Folder - but that is nothing I want to do every time.

### PR DESCRIPTION
**Pull request by tophf**
Fixes #1247.

### CODE REVIEW

File: background/sync-manager.js [hunk 1]
```diff
@@ -40,9 +41,14 @@ const syncMan = (() => {
...
-  chrome.alarms.onAlarm.addListener(info => {
-    if (info.name === 'syncNow') {
-      syncMan.syncNow();
+  chrome.alarms.onAlarm.addListener(async ({name}) => {
+    if (name === 'syncNow') {
+      await syncMan.syncNow();
+      /* We want to fire the alarm once per SYNC_INTERVAL at a random point within the range,
+       * so the new delay includes the leftover portion from the last range. */
+      const r = Math.random();
+      schedule(SYNC_DELAY + SYNC_INTERVAL * (1 - lastInterval + r));
```
Comment (eight04) [inline background/sync-manager.js:50]: Suppose the collision happens when two syncs start in 1 minute ~= 30mins * 0.033. The probability of the collision will be `1^2 - (1-0.033)^2 = 0.064911`, which is 1 collision every ~15.4 sync (1 collision every 7.7 hours).

I think it is better to use a fixed interval and implement something like exponential backoff.

Comment (tophf) [reply background/sync-manager.js:50]: Maybe it'd be better to implement it in db-in-cloud?

Comment (narcolepticinsomniac) [reply background/sync-manager.js:50]: What's the verdict on this one? Is it something we should resolve before pushing a beta, or can it wait?

Comment (tophf) [reply background/sync-manager.js:50]: Well, since db-in-cloud is still not fixed I guess I'll implement the workaround as suggested above. Today, hopefully.

Comment (tophf) [reply background/sync-manager.js:50]: OTOH the probability of a collision is infinitely smaller because `delayInMinutes` is a fractional value, not an integer...

Comment (tophf) [reply background/sync-manager.js]: @eight04, could you take a look at the new code?
@narcolepticinsomniac, I didn't test it, sync is ew 😝
