### PR TITLE
Fix missing FF favicons Closes #683

### LINKED ISSUE #683: Add the Stylus favicon to its manage page ?
* **waterfox 56.2.8**:
* **Win10 64**:
* **1.5.2**:
I pined the manage styles of Stylus.
But their is no favicon for it (blank).
Can we have it, like that i can show what pined tab is concerned

### PR DESCRIPTION
**Pull request by narcolepticinsomniac**
I think the combo of  swapping `window.prefs` for `prefs`, and moving the function inside `onDOMready()` does the trick. 

@eight04 Any idea why `window.prefs` no longer works? Does the rest LGTY?

### CODE REVIEW

**Comment by eight04** [comment]
We used to use `var prefs` to define `prefs` object. Now we use `const` which doesn't attach the variable to the global object (`window`).

File: js/dom.js [hunk 1]
```diff
@@ -68,25 +68,24 @@ onDOMready().then(() => {
   $.remove('#firefox-transitions-bug-suppressor');
   initCollapsibles();
   focusAccessibility();
+  if (!chrome.app && chrome.windows) {
+    // add favicon in Firefox
+    setTimeout(() => {
+      if (!prefs) {
```
Comment (eight04) [inline js/dom.js]: Use `typeof` or this will throw a reference error when `prefs` is not defined.

File: js/dom.js [hunk 2]
```diff
@@ -68,25 +68,24 @@ onDOMready().then(() => {
   $.remove('#firefox-transitions-bug-suppressor');
   initCollapsibles();
   focusAccessibility();
+  if (!chrome.app && chrome.windows) {
+    // add favicon in Firefox
+    setTimeout(() => {
```
Comment (eight04) [inline js/dom.js]: Not sure what does `setTimeout` do. Maybe we can remove it.

File: js/dom.js [hunk 3]
```diff
@@ -68,25 +68,24 @@ onDOMready().then(() => {
...
+      if (!prefs) {
+        return;
+      }
+      const iconset = ['', 'light/'][prefs.get('iconset')] || '';
```
Comment (eight04) [inline js/dom.js]: Since the prefs is async initialized, we have to wait till the initialization complete.
