### PR TITLE
Change: switch to launchWebAuthFlow polyfill

### LINKED ISSUE #877: Firefox doesn't support chrome URL in launchWebAuthFlow anymore
I got an email from addons@mozilla.com

> In the past, developers were able to use their custom own redirect URL as the endpoint of identity.launchWebAuthFlow(), in which the access token or authorization code is delivered to the extension. Starting with the release of Firefox 75 on April 7, 2020, the API will no longer work if you supply your own redirect URL. You will need to use a redirect URL that is derived from your extension’s ID by using the identity.getRedirectURL API.
>
> This change will make the identity API for Firefox behave the same as it does for Chrome. It also provides incremental security improvements by ensuring the OAuth flow will only return to your add-on. 

Which means OneDrive login will be broken:
https://github.com/openstyles/stylus/blob/50aecffe4c850647d359a2b9cbfe9459fc936a6e/background/token-manager.js#L46-L48

We have to add FF redirect URL to OneDrive. We have to register a new App if it doesn't support multiple URLs.

### LINKED ISSUE #890: [Firefox for Android] Sync to cloud stuck at "Connecting...", doesn't show auth
* **Browser**: Firefox for Android Beta (Fennec) 68.7b1
* **Operating System**: Android 9
* **Stylus Version**: 1.5.10
* **Screenshot**: Screenshot_20200325-174636

The "sync to cloud" feature introduced in #787 doesn't seem to work on Firefox for Android. Would be happy to help debug this if needed (if it can be made to work).

### PR DESCRIPTION
**Pull request by eight04**
Fixes #877
Fixes #890

I didn't test it on Firefox Android because currently it can't install extension.

Drawbacks:

> Currently there is no good way to create an "inactive minimized dialog" on both Chrome and Firefox. Ref: https://crbug.com/783827 & https://bugzilla.mozilla.org/show_bug.cgi?id=1659190

But I think it is better than dropping onedrive.

### CODE REVIEW

File: background/token-manager.js [hunk 1]
```diff
@@ -1,10 +1,11 @@
-/* global chromeLocal promisifyChrome FIREFOX */
+/* global chromeLocal promisifyChrome webextLaunchWebAuthFlow FIREFOX */
 /* exported tokenManager */
 'use strict';
 
 const tokenManager = (() => {
   promisifyChrome({
-    identity: ['launchWebAuthFlow'],
+    'browser.windows': ['create', 'update', 'remove'],
```
Comment (tophf) [inline background/token-manager.js:7]: Why `browser.`? It's not specified anywhere else.
