### PR TITLE
vivaldi bug workaround: open webAuth flow in a tab

### LINKED ISSUE #1182: Sync doesn't work in Vivaldi
* **Browser**: Vivaldi 3.4.2066.106 (Stable channel) (64-bit)
* **Operating System**: Arch Linux (everything is bleeding edge)
* **Stylus Version**: Any version using webext-launch-web-auth-flow

https://forum.vivaldi.net/topic/55513/does-not-trigger-onbeforerequest-for-popups

> So the workaround for Vivaldi would be to use type: 'normal', I guess.

First we have to make webext-launch-web-auth-flow accept a `mode: "popup" | "tab"` option.

### PR DESCRIPTION
**Pull request by tophf**
Fixes #1182.

### CODE REVIEW

**Comment by reaseno** [comment]
Doesn't work here. I copied the URL into a tab, but in the end I got a "The IP address of the server clngdbkpkpeebahjckkjfobafhncgmne.chromiumapp.org was not found." Same as without copying into a tab.

**Comment by tophf** [comment]
@reaseno that's not how you use a PR. You need to download the entire source code and install it as an unpacked extension.

**Comment by narcolepticinsomniac** [comment]
First time testing Vivaldi. LGTM.

File: background/token-manager.js [hunk 1]
```diff
@@ -203,4 +214,28 @@ const tokenMan = (() => {
     err.code = r.status;
     throw err;
   }
+
+  async function detectVivaldiWebRequestBug() {
```
Comment (eight04) [inline background/token-manager.js:218]: How about moving bug detection logic/state into `toolbox.js`? Therefore we can do something like:
```js
/* global hasVivaldiBug */ // toolbox.js

await webextLaunchWebAuthFlow({
  ...
  alwaysUseTab: await hasVivaldiBug()
})
```

**Review by eight04 — APPROVED** [review]
The code LGTM. Also tested with Dropbox+Vivaldi/Dropbox+Firefox and confirmed it works.

File: background/token-manager.js (hunk 1 above)
Comment (tophf) [reply background/token-manager.js:218]: This detector is needed only for this webRequest bug. If someone reports a Vivaldi-specific bug in CSS/DOM/JS then of course we will move the detector. The probability of such a bug is very low, AFAICT, because Vivaldi is more about outer customization.
