### PR TITLE
fix and simplify .user.css URL installer

### LINKED ISSUE #855: Local .user.css file doesn't open in Chrome 80+
* **Browser**: Chrome 80.0.3987.106
* **Operating System**: macos
* **Stylus Version**: 1.5.7

After drop local file on the tab strip:
Screen Shot 2020-02-15 at 12 54 25 AM
In firefox everything works fine.

### PR DESCRIPTION
**Pull request by tophf**
Fixes #855. 

* The style code is always downloaded directly when possible. It's also more reliable than reading document.body.textContent in a content script where another extension (or a userscript) may have changed it.

* The installer opens in the same tab when it can. IIRC I was against this idea initially several years ago but now I believe it's better than fluttering of new tabs being opened and closed.

  In Firefox 68+ the original tab is still needed for `file://` URLs though. This is explained in an extra hint that's shown only in this particular case when live-reload option is enabled.

  Ironically Chrome 80+ does the opposite - both the content script and the main page context can't fetch their own `file://` URL and in [crbug/1049604](https://crbug.com/1049604) they decided it's working-as-intended so they've only added an internal switch that can be specified as a command line parameter (Chrome 81+):

  ```
  --enable-features=RelaxIsolatedWorldCorsInFileUrlLoaderFactory
  ```

* Drag'n'dropping usercss files into the manager is no longer supported as it never made much sense (live-reload was unavailable). Also gone are the lengthy explanations and convoluted available/unavailable states of the checkbox in the installer page. A straightforward warning is displayed in such a case: "To install the file, drop it on the tab strip (the area where the tab titles are shown)".

P.S. Didn't test it yet in Chrome 49 or FF53. Actually I only tested in Chrome Canary and FF stable.

### CODE REVIEW

File: background/background.js [hunk 1]
```diff
@@ -147,12 +136,22 @@ prefs.initializing.then(() => {
...
-navigatorUtil.onUrlChange(({tabId, frameId, transitionQualifiers}, type) => {
-  if (type === 'committed' && !frameId) {
+navigatorUtil.onUrlChange(({tabId, frameId, transitionQualifiers, url}, type) => {
+  if (type !== 'committed') {
+    msg.sendTab(tabId, {method: 'urlChanged'}, {frameId})
+      .catch(msg.ignoreError);
+  } else if (!frameId) {
+    if (url.includes('.user.') &&
+        /^(https?|file|ftps?):/.test(url) &&
+        /\.user\.(css|styl)$/.test(url.split(/[#?]/, 1)[0]) &&
```
Comment (eight04) [inline background/background.js]: We need a `URLS.isUsercssSource` function

File: background/background.js [hunk 2]
```diff
@@ -147,12 +136,22 @@ prefs.initializing.then(() => {
...
+        !`${tabIconFor(tabId).url}`.startsWith(URLS.installUsercss)) {
```
Comment (eight04) [inline background/background.js]: I think it's a bad idea to mix the installation logic with the tab icon logic. Let's split out tab icon logic to a different file e.g. `background/icon-manager.js`.

File: background/usercss-helper.js [hunk 3]
```diff
@@ -157,32 +138,20 @@
...
-      chromeLocal.setValue(key, {loading: true}),
-    ]).then(([code]) => {
-      chromeLocal.setValue(key, code);
-      setTimeout(() => chromeLocal.remove(key), TEMP_CODE_CLEANUP_DELAY);
+  window.openUsercssInstallPage = (tabId, url) =>
+    Promise.resolve(
+      url.startsWith('file:') ||
+      fetch(url, {method: 'HEAD'})
+        .then(r => /^text\/(css|plain)(;.*?)?$/i.test(r.headers.get('content-type'))))
+    .then(ok => ok && download(url))
```
Comment (eight04) [inline background/usercss-helper.js]: image
`download` can't handle `file://` URLs in Firefox so we still need a content script to get the code from the tab.

Comment (tophf) [reply background/usercss-helper.js]: I wonder why does it work for me then? Gonna investigate.

File: background/background.js (hunk 2 above)
Comment (tophf) [reply background/background.js]: This is something you can do later. As for me, I'm fine with simply renaming the variable to tabData.

File: background/background.js (hunk 1 above)
Comment (tophf) [reply background/background.js]: Do we? Currently this check is performed only in one place so adding a function to `URLS` that's present in all other pages may be an overkill.

Comment (tophf) [reply background/background.js]: Exposed it in usercssHelper.

File: install-usercss/install-usercss.js [hunk 4]
```diff
@@ -391,47 +317,80 @@
...
-      } else if (tab.url === tabUrl) {
-        location.reload();
+    }
+    function onPortDisconnect() {
+      chrome.tabs.get(tabId, tab => {
+        if (chrome.runtime.lastError) {
+          closeCurrentTab();
+        } else if (tab.url === initialUrl) {
+          location.reload();
+        }
```
Comment (eight04) [inline install-usercss/install-usercss.js]: Should we close the installer when the URL doesn't match?

File: install-usercss/install-usercss.js [hunk 5]
```diff
@@ -391,47 +317,80 @@
...
+        filePort.postMessage('timer');
+      } else {
+        download(initialUrl).then(update, logError);
       }
-    });
+    }
+    function logError(error) {
+      console.warn(t('liveReloadError', error));
+    }
+    function start(reset) {
```
[the remark this answers is not in the document]
Comment (eight04) [reply install-usercss/install-usercss.js]: It might be better to rename `start` to `schedule` and `reset` to `force`.

File: install-usercss/install-usercss.js [hunk 6]
```diff
@@ -1,46 +1,25 @@
...
   const params = new URLSearchParams(location.search.replace(/^\?/, ''));
-  let liveReload = false;
+  const tabId = params.has('tabId') ? Number(params.get('tabId')) : -1;
+  const initialUrl = params.get('updateUrl');
+  if (!initialUrl) throw 'No updateUrl parameter';
+
   let installed = null;
   let installedDup = null;
+  let initialized = false;
+  let filePort;
```
Comment (eight04) [inline install-usercss/install-usercss.js]: I guess this should be moved into livereload as `livereload.filePort`?

File: js/msg.js [hunk 7]
```diff
@@ -242,6 +242,7 @@ self.API = self.INJECTED === 1 ? self.API : new Proxy({
   // Handlers for these methods need sender.tab.id which is set by `send` as it uses messaging,
   // unlike `sendBg` which invokes the background page directly in our own extension tabs
   getTabUrlPrefix: true,
+  getUsercssInstallCode: true,
```
Comment (eight04) [inline js/msg.js]: Is this still true?

File: background/usercss-helper.js [hunk 8]
```diff
@@ -1,42 +1,66 @@
-/* global API_METHODS usercss chromeLocal styleManager FIREFOX deepCopy openURL
-  download */
+/* global API_METHODS usercss styleManager deepCopy openURL download URLS getTab promisify */
+/* exports usercssHelper */
 'use strict';
 
-(() => {
+// eslint-disable-next-line no-unused-vars
+const usercssHelper = (() => {
+  // detecting FF68 by the added feature as navigator.ua may be spoofed via about:config or devtools
```
[the remark this answers is not in the document]
Comment (tophf) [reply background/usercss-helper.js]: I don't think so. We can't guess what decision they will make. Chrome, for one, makde an opposite choice and forbade fetching from tabs their own file URLs.

File: background/usercss-helper.js [hunk 9]
```diff
@@ -1,42 +1,66 @@
...
+        /^(https?|file|ftps?):/.test(url) &&
+        /\.user\.(css|styl)$/.test(url.split(/[#?]/, 1)[0]) &&
+        !url.startsWith(URLS.installUsercss);
+    },
+
+    openInstallerPage(tabId, url) {
+      const isFile = url.startsWith('file:');
+      const isFileFF = isFile && tabExec;
+      return Promise.resolve(isFile || fetch(url, {method: 'HEAD'}).then(isPlainCssResponse))
+        .then(ok => ok && (isFileFF ? tabExec(tabId, downloadSelf) : download(url)))
```
[the remark this answers is not in the document]
Comment (tophf) [reply background/usercss-helper.js]: I tried that already but then decided that current code is perfectly clear.

File: background/usercss-helper.js [hunk 10]
```diff
@@ -1,42 +1,66 @@
...
+          if (Array.isArray(code)) code = code[0];
+          if (!/==userstyle==/i.test(code)) return;
+          const newUrl = `${URLS.installUsercss}?updateUrl=${encodeURIComponent(url)}`;
+          if (isFileFF) {
+            getTab(tabId).then(tab =>
+              openURL({
+                url: `${newUrl}&tabId=${tabId}`,
+                active: tab.active,
+                index: tab.index + 1,
+                openerTabId: tabId,
```
[the remark this answers is not in the document]
Comment (tophf) [reply background/usercss-helper.js]: Someone broke it when I wasn't around - was it you? Anyway this is definitely not a part of this PR.

File: background/usercss-helper.js [hunk 11]
```diff
@@ -1,42 +1,66 @@
...
-        setTimeout(poll, TEMP_CODE_CLEANUP_DELAY);
-        return;
-      }
-      chrome.storage.local.get(null, storage => {
-        const leftovers = [];
-        for (const key in storage) {
-          if (key.startsWith(TEMP_CODE_PREFIX)) {
-            leftovers.push(key);
+  API_METHODS.getUsercssInstallCode = url => {
+    const {code, timer} = installCodeCache.get(url) || {};
```
[the remark this answers is not in the document]
Comment (tophf) [reply background/usercss-helper.js]: No. It's perfectly fine if the installer tab reloads in the future.

File: content/download-self.js [hunk 12]
```diff
@@ -0,0 +1,23 @@
+'use strict';
+
+// preventing reinjection by tabs.executeScript, just in case
+typeof self.oldCode !== 'string' && // eslint-disable-line no-unused-expressions
```
[the remark this answers is not in the document]
Comment (tophf) [reply content/download-self.js]: We don't have to. You're adding two levels of nesting for what? Only to avoid using eslint comment? I'd rather disable this nonsensical rule in eslint config.

File: content/download-self.js [hunk 13]
```diff
@@ -0,0 +1,23 @@
...
+  const postBack = msg => {
+    port.postMessage(msg);
+    self.oldCode = msg.code;
+  };
+  port.onMessage.addListener(cmd => {
+    const oldCode = cmd === 'timer' ? self.oldCode : '';
+    fetch(location.href, {mode: 'same-origin'})
+      .then(read)
+      .then(code => ({code: code === oldCode ? '' : code}), wrapError)
+      .then(postBack);
```
[the remark this answers is not in the document]
Comment (tophf) [reply content/download-self.js]: The installer tab may be reloaded and ask for the full code so even if it didn't change.

File: install-usercss/install-usercss.js [hunk 14]
```diff
@@ -1,46 +1,25 @@
...
 
 (() => {
-  const DUMMY_URL = 'foo:';
-
   // TODO: remove .replace(/^\?/, '') when minimum_chrome_version >= 52 (https://crbug.com/601425)
   const params = new URLSearchParams(location.search.replace(/^\?/, ''));
-  let liveReload = false;
+  const tabId = params.has('tabId') ? Number(params.get('tabId')) : -1;
+  const initialUrl = params.get('updateUrl');
+  if (!initialUrl) throw 'No updateUrl parameter';
```
[the remark this answers is not in the document]
Comment (tophf) [reply install-usercss/install-usercss.js]: Definitely not. It doesn't make any difference since this is a fatal exception that no one will catch. I'd rather remove this entire line because if some user tried to mess around they should accept the consequences of things totally breaking.

File: install-usercss/install-usercss.js [hunk 15]
```diff
@@ -391,47 +317,80 @@
...
+      console.warn(t('liveReloadError', error));
+    }
+    function start(reset) {
+      timer = !reset && timer || setTimeout(check, DELAY);
+    }
+    function stop() {
+      clearTimeout(check);
+      timer = 0;
+    }
+    function update(code) {
```
[the remark this answers is not in the document]
Comment (tophf) [reply install-usercss/install-usercss.js]: Right, I've lost the check.

File: install-usercss/install-usercss.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (tophf) [reply install-usercss/install-usercss.js]: Nope. That would be an unnecessary overcomplication. I'll just remove this parameter.

File: install-usercss/install-usercss.js [hunk 16]
```diff
@@ -391,47 +317,80 @@
...
+      } else {
+        download(initialUrl).then(update, logError);
       }
-    });
+    }
+    function logError(error) {
+      console.warn(t('liveReloadError', error));
+    }
+    function start(reset) {
+      timer = !reset && timer || setTimeout(check, DELAY);
```
[the remark this answers is not in the document]
Comment (tophf) [reply install-usercss/install-usercss.js]: I disagree but anyway this was fixed by removing the parameter altogether.

File: install-usercss/install-usercss.js [hunk 17]
```diff
@@ -391,47 +317,80 @@
...
+    }
+    function stop() {
+      clearTimeout(check);
```
[the remark this answers is not in the document]
Comment (tophf) [reply install-usercss/install-usercss.js]: Oops.

File: install-usercss/install-usercss.js [hunk 18]
```diff
@@ -54,8 +33,13 @@
       href: `vendor/codemirror/theme/${theme}.css`
     }));
   }
-  let liveReloadPending = Promise.resolve();
   window.addEventListener('resize', adjustCodeHeight);
+  // "History back" in Firefox (for now) restores the old DOM including the messagebox,
+  // which stays after installing since we don't want to wait for the fadeout animation before resolving.
+  document.addEventListener('visibilitychange', () => {
+    if (messageBox.element) messageBox.element.remove();
+    if (installed) liveReload.onToggled();
```
[the remark this answers is not in the document]
Comment (tophf) [reply install-usercss/install-usercss.js]: Firefox-specific as indicated in the comment. It restores everything, checkboxes included.

File: install-usercss/install-usercss.js [hunk 19]
```diff
@@ -1,46 +1,25 @@
...
-      }
-    });
-    port.onDisconnect.addListener(onPortDisconnected);
-  }
+  const liveReload = initLiveReload();
+
+  // when this tab is reloaded, bg may no longer have the code as it's kept only for a few seconds
+  API.getUsercssInstallCode(initialUrl)
+    .then(code => code || !filePort && download(initialUrl))
+    .then(code => (code || !filePort) && initSourceCode(code));
```
[the remark this answers is not in the document]
Comment (tophf) [reply install-usercss/install-usercss.js]: I disagree: multiple returns is a bad thing. Using throws for flow control is also a bad thing.

File: install-usercss/install-usercss.js [hunk 20]
```diff
@@ -64,35 +48,6 @@
     }
   }, 200);
 
-  getTab(tabId).then(tab => (tabUrl = tab.url));
-  chrome.tabs.onUpdated.addListener((id, {url}) => {
-    if (id === tabId && url && url !== tabUrl) {
-      closeCurrentTab();
-    }
-  });
-  // close the tab in case the port didn't report onDisconnect
```
[the remark this answers is not in the document]
Comment (tophf) [reply install-usercss/install-usercss.js]: I have no idea and I never remove things that ain't broke in a PR that's not about this particular thing.

File: install-usercss/install-usercss.js [hunk 21]
```diff
@@ -391,47 +317,80 @@
...
-      const code = data && data[key];
-
-      // bg already downloaded the code
-      if (typeof code === 'string') {
+  function initLiveReload() {
+    const DELAY = 500;
+    let isEnabled = false;
+    let timer = 0;
+    let sequence = Promise.resolve();
+    if (tabId >= 0) {
```
[the remark this answers is not in the document]
Comment (tophf) [reply install-usercss/install-usercss.js]: There's no need for backgroundDownloader as it only works once.

File: install-usercss/install-usercss.js (hunk 4 above)
Comment (tophf) [reply install-usercss/install-usercss.js]: I thought we didn't previously. I have no opinion on this particular thing but generally I prefer not to change behavior out of the blue.

File: install-usercss/install-usercss.js (hunk 6 above)
Comment (tophf) [reply install-usercss/install-usercss.js]: Yeah.

File: js/msg.js (hunk 7 above)
Comment (tophf) [reply js/msg.js]: Good catch. It no longer needs sender.

File: background/usercss-helper.js (hunk 11 above)
[the remark this answers is not in the document]
Comment (tophf) [reply background/usercss-helper.js]: Ah, you meant we can do it to simplify flow control.

File: install-usercss/install-usercss.js (hunk 19 above)
[the remark this answers is not in the document]
Comment (tophf) [reply install-usercss/install-usercss.js]: I've simplified it by implementing your suggestion to throw in getUsercssInstallCode.

File: content/download-self.js (hunk 12 above)
[the remark this answers is not in the document]
Comment (tophf) [reply content/download-self.js]: I've succumbed to one `if`.

File: content/download-self.js (hunk 13 above)
[the remark this answers is not in the document]
Comment (tophf) [reply content/download-self.js]: Reworked it.

File: install-usercss/install-usercss.js (hunk 21 above)
[the remark this answers is not in the document]
Comment (tophf) [reply install-usercss/install-usercss.js]: Implemented DirectDownloader and PortDownloader instead.

File: background/tab-manager.js [hunk 22]
```diff
@@ -0,0 +1,43 @@
...
+      try {
+        fn({tabId, url, oldUrl});
+      } catch (err) {
+        console.error(err);
+      }
+    }
+  });
+
+  return {
+    onUpdate(fn) {
```
Comment (tophf) [inline background/tab-manager.js]: Whenever possible use an inline function because jumping to definition or looking up function source and usages in IDE becomes a real PITA when using separate functions and a link.

File: background/usercss-helper.js (hunk 9 above)
[the remark this answers is not in the document]
Comment (tophf) [reply background/usercss-helper.js]: Then again any code can be refactored infinitely so I just reworked it again :-)

File: background/usercss-helper.js (hunk 10 above)
[the remark this answers is not in the document]
Comment (tophf) [reply background/usercss-helper.js]: Opened #859.

File: background/usercss-helper.js [hunk 23]
```diff
@@ -1,42 +1,66 @@
...
+        /\.user\.(css|styl)$/.test(url.split(/[#?]/, 1)[0]);
+    },
+
+    /** @return {Promise<{ code:string, inTab:boolean } | false>} */
+    testContents(tabId, url) {
+      const isFile = url.startsWith('file:');
+      const inTab = isFile && Boolean(fileLoader);
+      return Promise.resolve(isFile || fetch(url, {method: 'HEAD'}).then(isResponseText))
+        .then(ok => ok && (inTab ? fileLoader(tabId) : download(url)))
+        .then(code => /==userstyle==/i.test(code) && {code, inTab});
```
Comment (eight04) [inline background/usercss-helper.js]: The function may return `false`. It should be:
```js
.then(code => ({
  code: code && /==userstyle==/i.test(code) ? code : null,
  inTab
}));
```

File: background/usercss-helper.js [hunk 24]
```diff
@@ -1,42 +1,66 @@
...
+            url: `${newUrl}&tabId=${tabId}`,
+            active: tab.active,
+            index: tab.index + 1,
+            openerTabId: tabId,
+            currentWindow: null,
+          }));
+      } else {
+        const timer = setTimeout(clearInstallCode, 10e3, url);
+        installCodeCache[url] = {code, timer};
+        chrome.tabs.update(tabId, {url: newUrl});
```
Comment (eight04) [inline background/usercss-helper.js]: We can use `updateTab` here:
```js
updateTab(tabId, {url: newUrl}).catch(console.error);
```

File: content/download-self.js [hunk 25]
```diff
@@ -0,0 +1,23 @@
+'use strict';
+
+// preventing reregistration if reinjected by tabs.executeScript for whatever reason, just in case
+if (typeof self.oldCode !== 'string') {
+  chrome.runtime.onConnect.addListener(port => {
+    if (port.name !== 'downloadSelf') return;
+    const read = r => r.status === 200 ? r.text() : Promise.reject(r.status);
```
Comment (eight04) [inline content/download-self.js]: Let's use a real object with a better message:
```js
Promise.reject(new Error(`fetch error: invalid status ${r.status}`))
```

File: content/download-self.js [hunk 26]
```diff
@@ -0,0 +1,23 @@
...
+    const postBack = msg => {
+      port.postMessage(msg);
+      self.oldCode = msg.code;
+    };
+    port.onMessage.addListener(({id, timer}) => {
+      fetch(location.href, {mode: 'same-origin'})
+        .then(read)
+        .then(code => ({id, code: timer && code === self.oldCode ? null : code}))
+        .catch(error => ({id, error}))
```
Comment (eight04) [inline content/download-self.js]: Can we pass error objects through message port? If not then we have to convert the error to a simple object and convert it back (or throw) on receive.

File: content/download-self.js [hunk 27]
```diff
@@ -0,0 +1,23 @@
...
+        .then(postBack);
+    });
+  });
+}
+
+// this assignment also passes the result to tabs.executeScript
+self.oldCode = (document.querySelector('body > pre') || document.body).textContent;
```
Comment (eight04) [inline content/download-self.js]: This resets `oldCode` to the initial state when `oldCode` is already set and the content script is injected multiple times. It probably should be:
```js
self.oldCode = self.oldCode || (...);
```

File: install-usercss/install-usercss.js (hunk 18 above)
[the remark this answers is not in the document]
Comment (eight04) [reply install-usercss/install-usercss.js]: But if the listener is still in the memory, shouldn't the timer is still there too?

File: install-usercss/install-usercss.js (hunk 20 above)
[the remark this answers is not in the document]
Comment (eight04) [reply install-usercss/install-usercss.js]: Then I think we have to move this to `PortDownloader`. I think there is a bug that `port.onDisconnected` doesn't fire while the source tab navigates to a different URL.

[the remark this answers is not in the document]
Comment (eight04) [reply install-usercss/install-usercss.js]: I wonder if it is because Firefox keeps the document in the memory in this case. We may have to investigate this situation. We can delay this to a new issue.

File: install-usercss/install-usercss.js [hunk 28]
```diff
@@ -391,47 +308,103 @@
...
+        if (installed || installedDup) {
+          (isEnabled ? start : stop)();
+          $('.install').disabled = isEnabled;
+          $('#live-reload-install-hint').hidden = !isEnabled;
+          $('#live-reload-install-hint-ff').hidden = !isEnabled || tabId < 0;
+        }
+      },
+    };
+    function check() {
+      getData(initialUrl)
```
Comment (eight04) [inline install-usercss/install-usercss.js]: `getData` takes no arguments.

File: install-usercss/install-usercss.js [hunk 29]
```diff
@@ -391,47 +308,103 @@
...
+    function start() {
+      timer = timer || setTimeout(check, DELAY);
+    }
+    function stop() {
+      clearTimeout(timer);
+      timer = 0;
+    }
+    function update(code) {
+      if (code == null) return;
+      sequence = sequence.then(() => {
```
Comment (eight04) [inline install-usercss/install-usercss.js]: Once something throws `sequence` will be break. We should catch the error before adding a new promise:
```js
sequence = sequence.catch(console.error).then(() => {
  ...
})
```

File: install-usercss/install-usercss.js [hunk 30]
```diff
@@ -391,47 +308,103 @@
...
-      } else if (tab.url === tabUrl) {
-        location.reload();
-      }
-    });
+        });
+      });
+      return () => new Promise((resolve, reject) => {
+        const id = performance.now();
+        resolvers.set(id, {resolve, reject});
+        port.postMessage({id, timer: true});
```
Comment (eight04) [inline install-usercss/install-usercss.js]: If `timer` is always `true` then I think we can remove this parameter.

File: background/background.js [hunk 31]
```diff
@@ -87,23 +81,23 @@ var browserCommands, contextMenus;
...
-    // styles would be updated when content script is injected.
-    return;
+  if (type !== 'committed') {
+    msg.sendTab(tabId, {method: 'urlChanged'}, {frameId})
+      .catch(msg.ignoreError);
+  }
+});
+
+tabManager.onUpdate(({tabId, url, oldUrl = ''}) => {
+  if (usercssHelper.testUrl(url) && !oldUrl.startsWith(URLS.installUsercss)) {
```
[the remark this answers is not in the document]
Comment (tophf) [reply background/background.js]: Yep.

File: background/icon-manager.js [hunk 32]
```diff
@@ -0,0 +1,101 @@
+/* global prefs debounce iconUtil FIREFOX CHROME VIVALDI tabManager */
+/* exported iconManager */
+'use strict';
+
+const iconManager = (() => {
+  const ICON_SIZES = FIREFOX || CHROME >= 2883 && !VIVALDI ? [16, 32] : [19, 38];
+
+  prefs.subscribe([
```
[the remark this answers is not in the document]
Comment (tophf) [reply background/icon-manager.js]: Dunno. I haven't analyzed the current code and I don't really remember the old one.

File: background/usercss-helper.js [hunk 33]
```diff
@@ -1,42 +1,66 @@
...
+        /^(https?|file|ftps?):/.test(url) &&
+        /\.user\.(css|styl)$/.test(url.split(/[#?]/, 1)[0]);
+    },
+
+    /** @return {Promise<{ code:string, inTab:boolean } | false>} */
+    testContents(tabId, url) {
+      const isFile = url.startsWith('file:');
+      const inTab = isFile && Boolean(fileLoader);
+      return Promise.resolve(isFile || fetch(url, {method: 'HEAD'}).then(isResponseText))
+        .then(ok => ok && (inTab ? fileLoader(tabId) : download(url)))
```
[the remark this answers is not in the document]
Comment (tophf) [reply background/usercss-helper.js]: It looks like Java or C# or TypeScript and I don't like this. There's also too many question marks.

File: background/usercss-helper.js (hunk 23 above)
Comment (tophf) [reply background/usercss-helper.js]: Nope, it's perfectly fine to use test() directly because it stringifies its argument. This is how JavaScript works, it's not C# or python or Java.

File: background/usercss-helper.js (hunk 24 above)
Comment (tophf) [reply background/usercss-helper.js]: Why do you add a catch here? It should be printed to the console by default as a noncaught exception.

File: content/download-self.js (hunk 25 above)
Comment (tophf) [reply content/download-self.js]: Let us not. `Error` is not transferable. Also there's no need to reject with an `Error` as any rejection is an error. This advice you're trying to follow is for the case when there's only one result variable that can take both data and error.

File: content/download-self.js (hunk 26 above)
Comment (tophf) [reply content/download-self.js]: No we can't and I we shouldn't as I explained above.

File: content/download-self.js (hunk 27 above)
Comment (tophf) [reply content/download-self.js]: Not really, it'll just cause the correct current code to be sent once again to the port. This construction is also dangerous as it may resolve to an element in DOM with `id="oldCode"` so I would have to use another check or use an IIFE which I really don't want to. Let's keep it simple, just the way it is.

File: install-usercss/install-usercss.js (hunk 29 above)
Comment (tophf) [reply install-usercss/install-usercss.js]: What exactly throws? The last part in sequence is `.catch(showError)` and if something throws there it would mean an unrecoverable bug anyway.

File: install-usercss/install-usercss.js (hunk 30 above)
Comment (tophf) [reply install-usercss/install-usercss.js]: Eek, it's a bug.

File: install-usercss/install-usercss.js (hunk 18 above)
[the remark this answers is not in the document]
Comment (tophf) [reply install-usercss/install-usercss.js]: Apparently timers aren't restored.

File: background/usercss-helper.js (hunk 8 above)
[the remark this answers is not in the document]
Comment (tophf) [reply background/usercss-helper.js]: Well, you're right, there's no need to treat ancient versions differently.

File: content/download-self.js (hunk 27 above)
Comment (tophf) [reply content/download-self.js]: Resolved by moving it inside `if`.

File: background/usercss-helper.js (hunk 23 above)
Comment (tophf) [reply background/usercss-helper.js]: Promise-based code is inherently awkward and clumsy so the real solution is to switch to async/await:

```js
    async testContents(tabId, url) {
      const isFile = url.startsWith('file:');
      const inTab = isFile && Boolean(fileLoader);
      if ((isFile || isResponseText(await fetch(url, {method: 'HEAD'}))) &&
          /==userstyle==/i.test(await inTab ? fileLoader(tabId) : download(url))) {
        return {code, inTab};
      }
    },
```

Comment (eight04) [reply background/usercss-helper.js]: What is the signature of `testContents`? If you want to allow the function to return `null/undefined` then the code using it needs to be changed:
https://github.com/openstyles/stylus/blob/01873ae8e8f7374b141fdb921100ecc53d1a78ab/background/background.js#L94-L96

----

To write clean callback code, you can refactor phases into functions:
```js
testContents(tabId, url) {
  const isFile = url.startsWith('file:');
  const inTab = isFile && Boolean(fileLoader);
  return testSourceContent().then(ok => {
    if (ok) {
      return downloadCode().then(code => ({
        code: /==userstyle==/i.test(code) ? code : null,
        inTab
      }));
    }
  });
  
  function testSourceContent() {
    return isFile ? Promise.resolve(true) :
      fetch(url, {method: 'HEAD'}).then(isResponseText);
  }
  
  function downloadCode() {
    return inTab ? fileLoader(tabId) : download(url);
  }
}
```

File: install-usercss/install-usercss.js (hunk 29 above)
Comment (eight04) [reply install-usercss/install-usercss.js]: Then let's move the `catch` to the outside to catch all errors:
```diff
diff --git a/install-usercss/install-usercss.js b/install-usercss/install-usercss.js
index 95916aee..569ea2d7 100644
--- a/install-usercss/install-usercss.js
+++ b/install-usercss/install-usercss.js
@@ -368,9 +368,8 @@
         cm.setCursor(cursor);
         cm.scrollTo(scrollInfo.left, scrollInfo.top);
         return API.installUsercss({id, sourceCode: code})
-          .then(updateMeta)
-          .catch(showError);
-      });
+          .then(updateMeta);
+      }).catch(showError);
     }
     function DirectDownloader() {
       let oldCode = null;

```

File: content/download-self.js (hunk 25 above)
Comment (eight04) [reply content/download-self.js]: > any rejection is an error

`Promise.reject` doesn't wraps the content to an error object. We still have to create an error object manually.

File: content/download-self.js (hunk 26 above)
Comment (eight04) [reply content/download-self.js]: This is not related to the previous problem. JavaScript creates an error object when something went wrong including `fetch()`, `.text()`.

File: content/install-hook-usercss.js [hunk 34]
```diff
@@ -1,123 +1,24 @@
...
-      xhr.send();
+// preventing reregistration if reinjected by tabs.executeScript for whatever reason, just in case
+if (typeof self.oldCode !== 'string') {
+  self.oldCode = (document.querySelector('body > pre') || document.body).textContent;
+  chrome.runtime.onConnect.addListener(port => {
+    if (port.name !== 'downloadSelf') return;
+    const read = r => r.status === 200 ? r.text() : Promise.reject(r.status);
+    const postBack = msg => {
+      port.postMessage(msg);
+      self.oldCode = msg.code;
```
Comment (eight04) [inline content/install-hook-usercss.js]: We can't blindly set `oldCode` to `msg.code` since it may contain `null`. When `oldCode` is set to `null`, the `typeof` check will be broken and the next call of `getData({timer: true})` will always get the code even if the code is not changed.

File: install-usercss/install-usercss.js (hunk 20 above)
[the remark this answers is not in the document]
Comment (eight04) [reply install-usercss/install-usercss.js]: #864

File: background/usercss-helper.js (hunk 23 above)
Comment (tophf) [reply background/usercss-helper.js]: 1) The signature is given in the JSDoc comment, start using it already. 2) Your example code is only superficially clean because it simply adds a few empty lines and gives names to intermediate things, the same can be achieved by adding comments in the original code. I often use such separation myself but it's not needed here because the code is already trivial, no need to nitpick on it.

File: install-usercss/install-usercss.js (hunk 29 above)
Comment (tophf) [reply install-usercss/install-usercss.js]: showError catches for installUsercss, it doesn't catch for anything else. I'm getting tired of this so let's assume you were right initially.

File: content/install-hook-usercss.js (hunk 34 above)
Comment (tophf) [reply content/install-hook-usercss.js]: Right.

File: content/download-self.js (hunk 25 above)
Comment (tophf) [reply content/download-self.js]: Like I said there's no need to use an `Error` object here. It doesn't offer any benefits except unnecessary complications in this case. No need to blindly follow "best practices", it's actually counter-productive and harmful.

File: content/download-self.js (hunk 26 above)
Comment (tophf) [reply content/download-self.js]: Like I said, you need to understand why something is used, not just copy it because something else is doing it. The low-level things and libraries use `Error` object also because they must provide all that extra info inside the object like the call stack and a universal interface to testing/examining the error. We don't need it here.

File: background/background.js [hunk 35]
```diff
@@ -87,23 +81,23 @@ var browserCommands, contextMenus;
...
+    usercssHelper.testContents(tabId, url).then(data => {
+      if (data.code) usercssHelper.openInstallerPage(tabId, url, data);
```
Comment (eight04) [inline background/background.js]: `data` can be `false` so we need `if (data && data.code) ...`.

Comment (tophf) [reply background/background.js]: No, `false` is perfectly fine as you can see in console: `(false).constructor`.
Only `null` and `undefined` can't have properties.

Comment (eight04) [reply background/background.js]: I think we have a disagreement about "perfectly fine".

Comment (tophf) [reply background/background.js]: I meant there's no technical `need` for the change.
